<?PHP
$CON=MYSQLI_CONNECT("LOCALHOST","ADMIN","?");
// CHECK CONNECTION
IF (MYSQLI_CONNECT_ERRNO()) {
  ECHO "FAILED TO CONNECT TO MYSQL: " . MYSQLI_CONNECT_ERROR();
}

// CREATE DATABASE
$SQL="CREATE DATABASE CORRAL_PROJECT";
IF (MYSQLI_QUERY($CON,$SQL)) {
  ECHO "CORRAL_PROJECT CREATED SUCCESSFULLY";
} ELSE {
  ECHO "ERROR CREATING CORRAL_PROJECT DATABASE: " . MYSQLI_ERROR($CON);
}

// CREATE TABLE

$CON=MYSQLI_CONNECT("LOCALHOST","ADMIN","?","CORRAL_PROJECT");
// CHECK CONNECTION
IF (MYSQLI_CONNECT_ERRNO()) {
  ECHO "FAILED TO CONNECT TO MYSQL: " . MYSQLI_CONNECT_ERROR();
}

$SQL = "CREATE TABLE STUDENT (
STUDENT_ID INT NOT NULL AUTO_INCREMENT,
STUDENT_NUM INT NOT NULL,
STUDENT_FIRSTNAME VARCHAR(20) NOT NULL,
STUDENT_LASTNAME VARCHAR(20) NOT NULL,
STUDENT_EMAIL VARCHAR(35) NOT NULL,
PRIMARY KEY (STUDENT_ID))";

// EXECUTE QUERY
IF (MYSQLI_QUERY($CON,$SQL)) {
  ECHO "<P>STUDENT TABLES CREATED SUCCESSFULLY</P>";
} ELSE {
  ECHO "ERROR CREATING STUDENT TABLE: " . MYSQLI_ERROR($CON);
}

?>
