<?PHP
$CON=MYSQLI_CONNECT("LOCALHOST","ADMIN","PASSWORD1","CORRAL_PROJECT");
// CHECK CONNECTION
IF (MYSQLI_CONNECT_ERRNO()) {
  ECHO "FAILED TO CONNECT TO MYSQL: " . MYSQLI_CONNECT_ERROR();
}

MYSQLI_QUERY($CON,"INSERT INTO STUDENT (STUDENT_NUM, STUDENT_FIRSTNAME, STUDENT_LASTNAME, STUDENT_EMAIL)
VALUES (21234, 'PETER', 'GRIFFIN', 'MARC_411@')");

// EXECUTE QUERY
IF (MYSQLI_QUERY($CON)) {
  ECHO "<P>STUDENT TABLES CREATED SUCCESSFULLY</P>";
} ELSE {
  ECHO "ERROR CREATING STUDENT TABLE: " . MYSQLI_ERROR($CON);
}

?>
