<?php
  $PageTitle = "Welcome to Corral";
  require "HEADER_PUBLIC.PHP"
?>
<div id="contents">
  <h2>Welcome to Corral</h2>
  <p>Corral is an application that provides staff with the ability to match students to projects with <br>
    no manual assigning required. Once a project and desired skills have been set, a student list <br>
    is imported before Corral automatically assigns the best candidates for the project.

    <br><br>
    Please read the email invitation carefully and follow the instructions to complete the required tasks.
  </div>
</div>

<hr>
<p>&nbsp;</p>

<?php require "FOOTER_PUBLIC.PHP" ?>
