<?php
  $PageTitle = "Welcome to Corral";
  require "HEADER_PUBLIC.PHP" 
?>
<div id="contents">
  <h2>Welcome to Corral</h2>
<p>This site aims to provide staff and students with a platform to view and request access to upcoming projects. Through this platform, staff and teachers may upload projects for students, including details of the skills sets and numbers required for the job. Students who register can then complete a quick survey to determine their levels or proficency in certain areas such as IT and communication. Corral takes this information, and provides Teachers with a list of suitable candidates for the positions available.


  <br><br>For more information, please click <a href="../PAGES/ABOUTUS">here</a></p>

  </div>
</div>

<hr>
<p>&nbsp;</p>

<?php require "FOOTER_PUBLIC.PHP" ?>
