<?php
    $PageTitle = "Sorting Setup";
    require "../PAGES/HEADER_STAFF.PHP";
?>
<div style="text-align: center; width: 100%;">
    <p>Welcome to the placeholder page for sorting setup.</p>
    <p>The settings you need are not yet implemented, so just click the start button.</p>
    <form action="BEGIN2.PHP" method="post" target="_blank">
        <input type="submit" value="Start Sorting" class="inputButton">
    </form>
</div>
<?php
    require "../PAGES/FOOTER_STAFF.PHP";
?>
