    <div style='width: 100%; text-align: center; font-family: sans-serif; font-size: 1em'>
        <br>
        <form action="iterate.php">
            <input type="submit" value="Continue Assign" style="font-size: 1.5em; background-color: white;">
        </form>
        <br>
        <?php
            require "iterate_table.php";
        ?>
   </div>

<?php require "../PAGES/FOOTER_STAFF.PHP"; ?>
